### ISSUE TITLE
提交一个问题

### ISSUE THREAD

**Issue by lxk0301** [BurpSuite/CloudGate-Shadowrocket#16]
你好 ,刚才  用你 提供的shadowrocket.conf  文件去广告(使用的APP是shadowrocket), 爱奇艺视频失败,还是  有 广告的

**Comment by BurpSuite** [comment]
不是说失效了，我把IP-CIDR去掉了，如果不去掉因为它的误拦，QQ 头像和QQ 空间图片都载入不出来，所以我决定去掉

**Comment by BurpSuite** [comment]
你不信可以试试，在Shadowrocket里导入Surge规则，然后再开启Log功能，然后你打开QQ清理下所有缓存，然后再代理上打开QQ，你再看看是不是都载入不了，然后你看看是不是一些没在规则里的请求都被REJECT了。

**Comment by lxk0301** [comment]
确实是的，刚才图片等等是加载不出来，之前也遇到过，具体是用的哪个软件忘记了，然后也没太在意

**Comment by lxk0301** [comment]
不知道你知不知道逗比极克的规则，也是一样，能去爱奇艺的广告。但是QQ等图片也加载不出来

**Comment by BurpSuite** [comment]
这个有人之前提起过，然后我看了一下，发现IP-CIDR被REJECT了，我发现我无法用任何方式解决掉此误拦，然后我就去掉了IP-CIDR，另外我也不认为是我的问题，我的规则和其他我的几款规则都是一样的，都是通过我自己写的PHP文件模块解析的，具体详细见API，所以我认为是Shadowrocket的问题，有需要可以自行联系Shadowrocket开发者。

**Comment by BurpSuite** [comment]
不太清楚，反正开发者不解决的话，规则也是解决不掉的。
